import React, { useEffect, useState } from 'react';
import { ArrowLeft, RefreshCw } from 'lucide-react';
import { fetchSupplierMonthDetails, type SupplierMonthSummary } from '../services/googleSheetsService';
import { useGoogleAuth } from '../contexts/GoogleAuthContext';

const fmtAmount = (n: number) => new Intl.NumberFormat('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(n);
const fmtWhole = (n: number) => new Intl.NumberFormat('en-US', { maximumFractionDigits: 0 }).format(n);
export const SupplierMonthDetailPage: React.FC<{ month: string; cutoffDate: string; onBack: () => void }> = ({ month, cutoffDate, onBack }) => {
  const { accessToken } = useGoogleAuth(); const [data, setData] = useState<SupplierMonthSummary | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const load = async () => { if (!accessToken) return; setLoading(true); try { setData(await fetchSupplierMonthDetails(accessToken, month, cutoffDate)); } catch (e: any) { setError(e.message || 'Failed to load details'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [accessToken, month, cutoffDate]);
  return <div className="w-full max-w-2xl mx-auto bg-white shadow-xl rounded-2xl overflow-hidden border border-gray-100 my-4 sm:my-8"><div className="p-4 bg-white border-b border-gray-100 flex items-center gap-4"><button onClick={onBack} className="p-2 text-gray-500"><ArrowLeft size={20}/></button><h1 className="text-lg font-bold text-gray-900 flex-1">{month}</h1><button onClick={load} disabled={loading} className="p-2 text-gray-500"><RefreshCw size={20} className={loading ? 'animate-spin' : ''}/></button></div>{loading ? <div className="py-20 text-center text-gray-400">Loading details...</div> : error ? <div className="py-20 text-center text-red-500">{error}</div> : data && <div className="text-[15px]"><div className="grid grid-cols-4 border-b border-gray-300 bg-gray-50 font-bold"><div className="p-3">MA-PAID</div><div className="p-3 text-right">AMOUNT</div><div className="p-3 text-right">JKB</div><div className="p-3 text-right">NCK</div></div>{data.items.map((item) => <div key={item.sourceRow} className="grid grid-cols-4 border-b border-gray-100"><div className="p-3">{item.date}</div><div className="p-3 text-right font-semibold">{fmtAmount(item.amount)}</div><div className="p-3 text-right">{fmtWhole(item.jkb)}</div><div className="p-3 text-right">{fmtWhole(item.nck)}</div></div>)}<div className="grid grid-cols-4 border-t-2 border-gray-900 bg-gray-50/50 font-bold"><div className="p-3">TOTAL</div><div className="p-3 text-right">{fmtAmount(data.amount)}</div><div className="p-3 text-right">{fmtWhole(data.jkb)}</div><div className="p-3 text-right">{fmtWhole(data.nck)}</div></div></div>}</div>;
};
